# Generated by Django 5.2.15 on 2026-06-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contenttemplate",
            new_name="templates_c_user_id_6f7d15_idx",
            old_name="templates_c_user_id_ef9fc8_idx",
        ),
        migrations.RenameIndex(
            model_name="contenttemplate",
            new_name="templates_c_user_id_5e4d15_idx",
            old_name="templates_c_user_id_742e64_idx",
        ),
    ]
