# Generated by Django 5.2.15 on 2026-06-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="brandprofile",
            new_name="brands_bran_user_id_e0eac3_idx",
            old_name="brands_bran_user_id_16cd67_idx",
        ),
        migrations.RenameIndex(
            model_name="brandprofile",
            new_name="brands_bran_created_8555a6_idx",
            old_name="brands_bran_created_18eeb0_idx",
        ),
    ]
