# Generated by Django 5.2.15 on 2026-06-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usageevent",
            new_name="usage_usage_user_id_399e4f_idx",
            old_name="usage_usage_user_id_95423d_idx",
        ),
        migrations.RenameIndex(
            model_name="usageevent",
            new_name="usage_usage_created_cca628_idx",
            old_name="usage_usage_created_1eb8c8_idx",
        ),
    ]
